services:
  # Servicio de Base de Datos
  db:
    image: postgres:15-alpine
    container_name: tienda_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tienda_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mi_red

  # Servicio de Aplicaci√≥n
  app:
    build: .
    container_name: tienda_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=tienda_db
    depends_on:
      - db
    networks:
      - mi_red

volumes:
  postgres_data:

networks:
  mi_red: